xrdr: Added -d :0 and -x /home/pschmitt/.Xauthority options

diff --git a/xrdr b/xrdr
--- a/xrdr
+++ b/xrdr
@@ -1,8 +1,7 @@
-#!/bin/bash -x
+#!/bin/bash
 # Author: Philipp Schmitt
 # Version: 1.5
 
-#USER=pschmitt
 CONFIG_FILE="/etc/conf.d/xrdr.conf"
 USER_CONFIG_FILE="$HOME/.config/xrdr.conf"
 
@@ -12,8 +11,6 @@ USER_CONFIG_FILE="$HOME/.config/xrdr.conf"
 
 [[ -r $USER_CONFIG_FILE ]] && . $USER_CONFIG_FILE || ( [[ -r $CONFIG_FILE ]] && . $CONFIG_FILE )
 
-[[ -z "$DISPLAY" ]] && export DISPLAY=:0
-[[ -z "$XAUTHORITY" ]] && export XAUTHORITY=$HOME/.Xauthority
 
 function check_screen_variables() {
     [[ -n "$PRIMARY_SCREEN" ]] && [[ "${SCREENS[@]}" =~ "$PRIMARY_SCREEN" ]] && local first_screen_ok=0
@@ -111,6 +108,30 @@ function auto() {
     [[ ${#SCREENS[@]} -gt 1 ]] && extend || primary_only
 }
 
+while getopts 'd:x:' opt ; do
+    case $opt in
+         d)
+            export DISPLAY="$OPTARG"
+            ;;
+        x)
+            export XAUTHORITY="$OPTARG"
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            exit 1
+            ;;
+        :)
+            echo "Option -$OPTARG requires an argument." >&2
+            exit 1
+            ;;
+    esac
+done
+
+shift $(($OPTIND - 1))
+
+[[ -z "$DISPLAY" ]] && export DISPLAY=:0
+[[ -z "$XAUTHORITY" ]] && export XAUTHORITY=$HOME/.Xauthority
+
 SCREENS=($(xrandr | grep " connected" | awk '{ print $1 }' | tr '\n' ' ' ))
 
 check_screen_variables || guess_screens
@@ -151,8 +172,8 @@ esac
 #[[ -n "$lbar_id" ]] && xkill -id $lbar_id
 #[[ -n "$rbar_id" ]] && xkill -id $rbar_id
 
-xmonad --restart &
-(sleep 2 && nitrogen --restore) &
+xmonad --restart 
+sleep 2 && nitrogen --restore 
 
 exit 0
 
